create table companies (id bigint generated by default as identity, address varchar(255) not null, country varchar(255) not null, email varchar(255), name varchar(255) not null, phone varchar(255), tin varchar(255), primary key (id))
create table goods (id bigint generated by default as identity, name varchar(255), uom_id bigint, primary key (id))
create table invoice_lines (id bigint generated by default as identity, amount_in_rub decimal(19,2), base_amount decimal(19,2) not null, currency varchar(255) not null, line_number varchar(255), quantity decimal(19,2) not null, good_id bigint, invoice_id bigint, primary key (id))
create table invoices (id bigint generated by default as identity, creation_date timestamp, issue_date date, is_reversed boolean, number varchar(255), reversed_date timestamp, update_date timestamp, company_issuer_id bigint, company_receiver_id bigint, primary key (id))
create table invoices_paymentmeans (invoice_id bigint not null, paymentmean_id bigint not null, primary key (invoice_id, paymentmean_id))
create table paymentmeans (id bigint generated by default as identity, description varchar(255), primary key (id))
create table uom (id bigint generated by default as identity, description varchar(255), uom_name varchar(255), primary key (id))
alter table goods add constraint FK8gvscy7cb644re9kikxi0qaks foreign key (uom_id) references uom
alter table invoice_lines add constraint FKekltynnqwpgn9e4wenjaggn0n foreign key (good_id) references goods
alter table invoice_lines add constraint FKsgudq2lwpa9wc92a23nggah1w foreign key (invoice_id) references invoices
alter table invoices add constraint FKhjui085o658935mh7rsqggqvt foreign key (company_issuer_id) references companies
alter table invoices add constraint FKnx6c0kmm3ej16j4mougj06ftv foreign key (company_receiver_id) references companies
alter table invoices_paymentmeans add constraint FKpwrnyaorlac3jfbufqehyqlfy foreign key (paymentmean_id) references paymentmeans
alter table invoices_paymentmeans add constraint FK2kl11gnuthvgp1fni6wic89tc foreign key (invoice_id) references invoices
create table companies (id bigint generated by default as identity, address varchar(255) not null, country varchar(255) not null, email varchar(255), name varchar(255) not null, phone varchar(255), tin varchar(255), primary key (id))
create table goods (id bigint generated by default as identity, name varchar(255), uom_id bigint, primary key (id))
create table invoice_lines (id bigint generated by default as identity, amount_in_rub decimal(19,2), base_amount decimal(19,2) not null, currency varchar(255) not null, line_number varchar(255), quantity decimal(19,2) not null, good_id bigint, invoice_id bigint, primary key (id))
create table invoices (id bigint generated by default as identity, creation_date timestamp, issue_date date, is_reversed boolean, number varchar(255), reversed_date timestamp, update_date timestamp, company_issuer_id bigint, company_receiver_id bigint, primary key (id))
create table invoices_paymentmeans (invoice_id bigint not null, paymentmean_id bigint not null, primary key (invoice_id, paymentmean_id))
create table paymentmeans (id bigint generated by default as identity, description varchar(255), primary key (id))
create table uom (id bigint generated by default as identity, description varchar(255), uom_name varchar(255), primary key (id))
alter table goods add constraint FK8gvscy7cb644re9kikxi0qaks foreign key (uom_id) references uom
alter table invoice_lines add constraint FKekltynnqwpgn9e4wenjaggn0n foreign key (good_id) references goods
alter table invoice_lines add constraint FKsgudq2lwpa9wc92a23nggah1w foreign key (invoice_id) references invoices
alter table invoices add constraint FKhjui085o658935mh7rsqggqvt foreign key (company_issuer_id) references companies
alter table invoices add constraint FKnx6c0kmm3ej16j4mougj06ftv foreign key (company_receiver_id) references companies
alter table invoices_paymentmeans add constraint FKpwrnyaorlac3jfbufqehyqlfy foreign key (paymentmean_id) references paymentmeans
alter table invoices_paymentmeans add constraint FK2kl11gnuthvgp1fni6wic89tc foreign key (invoice_id) references invoices
